server:
  port: 8082

spring:
  application:
    name: board-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/board_db}
    username: ${DB_USERNAME:yys7517}
    password: ${DB_PASSWORD:}

  # datasource와 같은 라인으로 앞으로 당기기
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 최상위(root) 레벨로 앞으로 당기기
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}